import React, { useState } from 'react';
import Header from './components/Header';
import ImageUpload from './components/ImageUpload';
import PromptControls from './components/PromptControls';
import { generateArchitecturalDesign } from './services/geminiService';
import { AppState, GeneratedImage } from './types';
import { ArrowLeft, Download, AlertCircle, RefreshCw } from 'lucide-react';

const App: React.FC = () => {
  const [appState, setAppState] = useState<AppState>(AppState.IDLE);
  const [sourceImage, setSourceImage] = useState<{ base64: string; mimeType: string } | null>(null);
  const [result, setResult] = useState<GeneratedImage | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleImageSelected = (base64: string, mimeType: string) => {
    setSourceImage({ base64, mimeType });
    setAppState(AppState.PREVIEW);
    setError(null);
  };

  const handleReset = () => {
    setAppState(AppState.IDLE);
    setSourceImage(null);
    setResult(null);
    setError(null);
  };

  const handleGenerate = async (prompt: string) => {
    if (!sourceImage) return;

    setAppState(AppState.GENERATING);
    setError(null);

    try {
      const { imageUrl, text } = await generateArchitecturalDesign(
        sourceImage.base64,
        sourceImage.mimeType,
        prompt
      );

      if (imageUrl) {
        setResult({
          imageUrl,
          description: text || undefined
        });
        setAppState(AppState.SUCCESS);
      } else {
        throw new Error("No image generated by the model. Try a different prompt.");
      }
    } catch (err: any) {
      console.error(err);
      setError(err.message || "Something went wrong during generation.");
      setAppState(AppState.ERROR);
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 pb-20">
      <Header />

      <main className="max-w-4xl mx-auto px-4 py-8">
        {/* IDLE STATE: Upload */}
        {appState === AppState.IDLE && (
          <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className="text-center space-y-2 mb-12">
              <h1 className="text-4xl font-bold text-slate-900 tracking-tight">
                Reimagine Your Space
              </h1>
              <p className="text-lg text-slate-500 max-w-2xl mx-auto">
                Upload a photo of your room or exterior. Let Gemini AI redesign it instantly according to your architectural vision.
              </p>
            </div>
            <ImageUpload onImageSelected={handleImageSelected} />
          </div>
        )}

        {/* PREVIEW & GENERATING STATE */}
        {(appState === AppState.PREVIEW || appState === AppState.GENERATING || appState === AppState.ERROR) && sourceImage && (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 animate-in fade-in zoom-in-95 duration-300">
            
            {/* Left Column: Source & Inputs */}
            <div className="space-y-6">
               <button 
                onClick={handleReset}
                className="flex items-center text-sm font-medium text-slate-500 hover:text-slate-800 transition-colors mb-2"
              >
                <ArrowLeft className="w-4 h-4 mr-1" /> Back to Upload
              </button>

              <div className="relative group rounded-2xl overflow-hidden shadow-md bg-slate-200">
                <img 
                  src={`data:${sourceImage.mimeType};base64,${sourceImage.base64}`} 
                  alt="Original" 
                  className="w-full h-64 object-cover"
                />
                <div className="absolute top-3 left-3 bg-black/50 backdrop-blur-md text-white text-xs font-bold px-3 py-1 rounded-full">
                  Original
                </div>
              </div>

              <PromptControls 
                onSubmit={handleGenerate} 
                isLoading={appState === AppState.GENERATING} 
              />
              
              {appState === AppState.ERROR && (
                <div className="bg-red-50 border border-red-200 text-red-700 p-4 rounded-xl flex items-start gap-3">
                  <AlertCircle className="w-5 h-5 flex-shrink-0 mt-0.5" />
                  <div>
                    <h4 className="font-semibold text-sm">Generation Failed</h4>
                    <p className="text-sm mt-1">{error}</p>
                    <button 
                      onClick={() => setAppState(AppState.PREVIEW)}
                      className="text-xs font-bold mt-2 underline"
                    >
                      Try Again
                    </button>
                  </div>
                </div>
              )}
            </div>

            {/* Right Column: Placeholder / Loading */}
            <div className="flex flex-col h-full min-h-[400px]">
               <div className="flex-1 rounded-2xl bg-white border border-slate-200 shadow-sm flex items-center justify-center p-8 text-center relative overflow-hidden">
                  {appState === AppState.GENERATING ? (
                    <div className="flex flex-col items-center">
                       <div className="w-16 h-16 border-4 border-blue-100 border-t-blue-600 rounded-full animate-spin mb-6"></div>
                       <h3 className="text-xl font-semibold text-slate-800 mb-2">Architecting...</h3>
                       <p className="text-slate-500 max-w-xs text-sm">
                         Gemini is analyzing the geometry and applying your design styles. This usually takes about 10-20 seconds.
                       </p>
                    </div>
                  ) : (
                    <div className="text-slate-400 flex flex-col items-center">
                       <div className="w-20 h-20 bg-slate-100 rounded-full flex items-center justify-center mb-4">
                          <RefreshCw className="w-8 h-8 opacity-20" />
                       </div>
                       <p>Your generated design will appear here</p>
                    </div>
                  )}
               </div>
            </div>
          </div>
        )}

        {/* SUCCESS STATE */}
        {appState === AppState.SUCCESS && result && sourceImage && (
          <div className="space-y-8 animate-in fade-in slide-in-from-bottom-8 duration-700">
             <div className="flex items-center justify-between">
                <button 
                  onClick={() => setAppState(AppState.PREVIEW)}
                  className="flex items-center text-sm font-medium text-slate-500 hover:text-slate-800 transition-colors"
                >
                  <ArrowLeft className="w-4 h-4 mr-1" /> Edit Request
                </button>
                <button 
                  onClick={handleReset}
                  className="text-sm font-medium text-blue-600 hover:text-blue-700"
                >
                  Start New Project
                </button>
             </div>

             <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                {/* Before */}
                <div className="space-y-3">
                  <h3 className="text-lg font-semibold text-slate-700 pl-1">Original Space</h3>
                  <div className="relative rounded-2xl overflow-hidden shadow-lg border-4 border-white bg-slate-100">
                     <img 
                      src={`data:${sourceImage.mimeType};base64,${sourceImage.base64}`} 
                      alt="Original" 
                      className="w-full h-auto object-cover"
                    />
                  </div>
                </div>

                {/* After */}
                <div className="space-y-3">
                  <h3 className="text-lg font-semibold text-blue-700 pl-1 flex items-center gap-2">
                    Design Proposal
                    <span className="bg-blue-100 text-blue-700 text-[10px] px-2 py-0.5 rounded-full uppercase tracking-wider font-bold">Generated</span>
                  </h3>
                  <div className="relative rounded-2xl overflow-hidden shadow-lg border-4 border-blue-500/30 bg-slate-100 group">
                     <img 
                      src={result.imageUrl} 
                      alt="Generated Design" 
                      className="w-full h-auto object-cover"
                    />
                    <div className="absolute inset-0 bg-black/0 group-hover:bg-black/10 transition-colors flex items-center justify-center opacity-0 group-hover:opacity-100">
                        <a 
                          href={result.imageUrl} 
                          download="archivision-design.png"
                          className="bg-white text-slate-900 px-6 py-3 rounded-full font-bold shadow-xl flex items-center gap-2 transform translate-y-4 group-hover:translate-y-0 transition-all"
                        >
                          <Download className="w-5 h-5" /> Download Design
                        </a>
                    </div>
                  </div>
                  {result.description && (
                    <div className="bg-white p-4 rounded-xl border border-slate-200 text-sm text-slate-600 mt-4 shadow-sm">
                      <span className="font-semibold text-slate-900 block mb-1">Architect's Note:</span>
                      {result.description}
                    </div>
                  )}
                </div>
             </div>
          </div>
        )}
      </main>
    </div>
  );
};

export default App;